-- Typed models for the LatchshotScreenshot SDK (LuaLS annotations).
--
-- GENERATED from the API model: main.kit.entity.<e>.fields{} and per-op
-- params (op.<name>.points[].g.params[]). Field/param types come from the
-- canonical type sentinels via @voxgig/sdkgen canonToType (source of truth:
-- @voxgig/apidef VALID_CANON). Annotations only — no runtime effect. Do not
-- edit by hand.

---@class Health
---@field active number
---@field concurrency number
---@field pending number

---@class HealthLoadMatch
---@field active? number
---@field concurrency? number
---@field pending? number

---@class MonitoringRequest
---@field changeContext? string
---@field createdAt string
---@field email string
---@field id number
---@field monitoringGoal string
---@field pageCount string
---@field pageUrl string
---@field publicPageAuthority boolean
---@field replyConsent boolean
---@field safetyAcknowledged boolean
---@field startBoundaryAcknowledged boolean
---@field status string
---@field updatedAt string

---@class MonitoringRequestCreateData
---@field changeContext? string
---@field createdAt string
---@field email string
---@field id number
---@field monitoringGoal string
---@field pageCount string
---@field pageUrl string
---@field publicPageAuthority boolean
---@field replyConsent boolean
---@field safetyAcknowledged boolean
---@field startBoundaryAcknowledged boolean
---@field status string
---@field updatedAt string

---@class PilotRequest
---@field acceptanceSample? string
---@field callSite string
---@field createdAt string
---@field currentContract? string
---@field email string
---@field expectedRenders? string
---@field id number
---@field language? string
---@field provider? string
---@field replyConsent boolean
---@field repositoryAuthority boolean
---@field repositoryUrl string
---@field requiredBehavior? string
---@field safetyAcknowledged boolean
---@field startBoundaryAcknowledged boolean
---@field status string
---@field updatedAt string

---@class PilotRequestCreateData
---@field acceptanceSample? string
---@field callSite string
---@field createdAt string
---@field currentContract? string
---@field email string
---@field expectedRenders? string
---@field id number
---@field language? string
---@field provider? string
---@field replyConsent boolean
---@field repositoryAuthority boolean
---@field repositoryUrl string
---@field requiredBehavior? string
---@field safetyAcknowledged boolean
---@field startBoundaryAcknowledged boolean
---@field status string
---@field updatedAt string

---@class Render
---@field blockAds? boolean
---@field blockChats? boolean
---@field blockTrackers? boolean
---@field darkMode? boolean
---@field delay? number
---@field format? string
---@field fullPage? boolean
---@field height? number
---@field hideCookieBanners? boolean
---@field hidePopups? boolean
---@field kind? string
---@field landscape? boolean
---@field paper? string
---@field quality? number
---@field reducedMotion? boolean
---@field scale? number
---@field scrollPage? boolean
---@field timeout? number
---@field url string
---@field waitUntil? string
---@field width? number

---@class RenderCreateData
---@field blockAds? boolean
---@field blockChats? boolean
---@field blockTrackers? boolean
---@field darkMode? boolean
---@field delay? number
---@field format? string
---@field fullPage? boolean
---@field height? number
---@field hideCookieBanners? boolean
---@field hidePopups? boolean
---@field kind? string
---@field landscape? boolean
---@field paper? string
---@field quality? number
---@field reducedMotion? boolean
---@field scale? number
---@field scrollPage? boolean
---@field timeout? number
---@field url string
---@field waitUntil? string
---@field width? number

---@class Rendering

---@class RenderingLoadMatch
---@field block_ad? boolean
---@field block_chat? boolean
---@field block_tracker? boolean
---@field dark_mode? boolean
---@field format? string
---@field full_page? boolean
---@field height? number
---@field hide_cookie_banner? boolean
---@field hide_popup? boolean
---@field quality? number
---@field scroll_page? boolean
---@field url string
---@field width? number

---@class SafetyReviewRequest
---@field createdAt string
---@field currentControls string
---@field desiredOutcome string
---@field email string
---@field id number
---@field language string
---@field primaryConcern string
---@field replyConsent boolean
---@field repositoryAuthority boolean
---@field repositoryUrl string
---@field routePath string
---@field runtime string
---@field safetyAcknowledged boolean
---@field startBoundaryAcknowledged boolean
---@field status string
---@field testEvidence string
---@field updatedAt string

---@class SafetyReviewRequestCreateData
---@field createdAt string
---@field currentControls string
---@field desiredOutcome string
---@field email string
---@field id number
---@field language string
---@field primaryConcern string
---@field replyConsent boolean
---@field repositoryAuthority boolean
---@field repositoryUrl string
---@field routePath string
---@field runtime string
---@field safetyAcknowledged boolean
---@field startBoundaryAcknowledged boolean
---@field status string
---@field testEvidence string
---@field updatedAt string

---@class Trial
---@field consent? boolean
---@field email string
---@field expectedRenders? string
---@field name? string
---@field useCase? string

---@class TrialCreateData
---@field consent? boolean
---@field email string
---@field expectedRenders? string
---@field name? string
---@field useCase? string

---@class Upgrade
---@field consent boolean
---@field createdAt string
---@field currentPlan string
---@field id number
---@field note? string
---@field requestedPlan string
---@field status string
---@field updatedAt string

---@class UpgradeCreateData
---@field consent boolean
---@field createdAt string
---@field currentPlan string
---@field id number
---@field note? string
---@field requestedPlan string
---@field status string
---@field updatedAt string

---@class Usage
---@field customer table
---@field links table
---@field upgradeRequest any
---@field usage table

---@class UsageLoadMatch
---@field customer? table
---@field links? table
---@field upgradeRequest? any
---@field usage? table

local M = {}

return M
